# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions

name: KUTTL
on:
  workflow_call:
    inputs:
      kubernetes-provider:
        required: true
        type: choice
        options:
          - GKE
          - OpenShift
        description: >
          TODO

      kubernetes:
        required: true
        type: string
        description: >
          The Kubernetes release … FIXME

      base-image-matrix:
        required: true
        type: string
        description: >
          JSON array of (OS) base images to test

      postgresql-matrix:
        required: true
        type: string
        description: >
          JSON array of PostgreSQL major versions to test

jobs:
  google-gke-setup:
    if: ${{ github.event.inputs.kubernetes-provider == 'GKE' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/google-gke
        with:
          stage: setup
          k8s-release: ${{ github.event.inputs.kubernetes }}

  test-ubi8:
    if: ${{ contains(fromJSON(github.event.inputs.base-image-matrix), 'ubi8') }}
    needs:
      - google-gke-setup
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        postgresql: ${{ fromJSON(github.event.inputs.postgresql-matrix) }}
    steps:
      - uses: actions/checkout@v3
      - id: namespace
        run: |
          # Create namespace, perhaps 'gh${{github.run_id}}-${{matrix.base-image}}-${{matrix.postgresql}}'
          echo ::set-output 'name=name::gh${{github.run_id}}-${{matrix.base-image}}-${{matrix.postgresql}}'

      - uses: actions/checkout@v3
        with:
          repository: CrunchyData/postgres-operator
          path: work/postgres-operator
          # TODO: select a git-ref for the installer and tests
          # FIXME: should these two things be separate?

      - run: |
          echo Deploy to '${{ steps.namespace.outputs.name }}'
          # TODO: calculate related images from '${{ matrix.base-image }}'
          make -C work/postgres-operator --dry-run deploy

      - env:
          KUTTL_PG_VERSION: ${{ inputs.postgresql }}
        run: |
          make -C work/postgres-operator --dry-run generate-kuttl check-kuttl

      - if: ${{ always() }}
        run: |
          # TODO: delete and wait for KUTTL namespaces…
          # Delete namespace
          echo kubectl delete namespace '${{ steps.namespace.output.name }}'

  test-ubi9:
    if: ${{ contains(fromJSON(github.event.inputs.base-image-matrix), 'ubi9') }}
    needs:
      - google-gke-setup
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo >&2 Not implemented!
          exit 1

  google-gke-teardown:
    if: ${{ always() }}
    needs:
      - google-gke-setup
      - test-ubi8
      - test-ubi9
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/google-gke
        with:
          stage: teardown
          k8s-release: ${{ github.event.inputs.kubernetes }}
