# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions

name: KUTTL
on:
  workflow_dispatch:
    inputs:
      kubernetes-provider:
        default: GKE
        required: true
        type: choice
        options:
          - GKE
          #- OpenShift
        description: >
          TODO
      kubernetes:
        default: latest
        required: true
        type: string
        description: >
          TODO


jobs:
  parameters:
    runs-on: ubuntu-latest
    steps:
      - env: { JSON: "${{ toJSON(github.event.inputs) }}" }
        run: |
          echo >> "${GITHUB_STEP_SUMMARY}" '```json'
          jq   >> "${GITHUB_STEP_SUMMARY}" <<< "${JSON}"
          echo >> "${GITHUB_STEP_SUMMARY}" '```'

  google-gke-matrix:
    if: ${{ github.event.inputs.kubernetes-provider == 'GKE' }}
    runs-on: ubuntu-latest
    outputs:
      kubernetes: ${{ steps.versions.outputs.versions }}
    steps:
      - uses: actions/checkout@v2
      - id: versions
        uses: ./.github/actions/google-gke
        with:
          stage: versions
          k8s-release: ${{ github.event.inputs.kubernetes }}

  google-gke-setup:
    needs: [google-gke-matrix]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        kubernetes: ${{ fromJSON(needs.google-gke-matrix.outputs.kubernetes) }}
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/google-gke
        with:
          stage: setup
          k8s-release: ${{ matrix.kubernetes }}

  kubernetes-setup:
    needs:
      - google-gke-setup
    runs-on: ubuntu-latest
    steps:
      - run: |
          # Create namespace, perhaps (somesuch-${{github.run_id}})
          # Deploy something

  kubernetes-teardown:
    if: ${{ always() }}
    needs: [kubernetes-setup]
    runs-on: ubuntu-latest
    steps:
      - run: |
          # Delete namespace, perhaps (somesuch-${{github.run_id}})

  google-gke-teardown:
    if: ${{ always() }}
    needs:
      - google-gke-matrix
      - google-gke-setup
      - kubernetes-teardown
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        kubernetes: ${{ fromJSON(needs.google-gke-matrix.outputs.kubernetes) }}
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/google-gke
        with:
          stage: teardown
          k8s-release: ${{ matrix.kubernetes }}
